# Generated by Django 4.2.3 on 2023-11-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('face', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sample', models.FileField(default=None, upload_to='audio/')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusiQuizApp.singers')),
            ],
        ),
    ]
